project:
  type: book

book:
  title: "RAG Book"
  author: "Yun Mi"
  date: "3/17/2026"
  chapters:
    - index.qmd
    - 01-introduction-to-rag.qmd
    - 02-data-preparation.qmd
    - 03-index-construction-and-optimization.qmd
    - 04-retrieval-optimization.qmd
    - 05-generation-integration.qmd
    - 06-rag-system-evaluation.qmd
    - 07-advanced-rag-architectures.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
